INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada) VALUES ('Lavar louças', 'MEDIUM', FALSE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada ) VALUES ('Depilar o pintcher', 'HIGH', TRUE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada) VALUES ('Organizar livros', 'MEDIUM', TRUE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada ) VALUES ('Passear com o pintcher', 'HIGH', TRUE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada) VALUES ('Viajar fds', 'HIGH', TRUE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada ) VALUES ('Academia', 'HIGH', TRUE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada) VALUES ('Organizar a casa', 'MEDIUM', TRUE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada ) VALUES ('CORRER', 'HIGH', FALSE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada) VALUES ('Organizar quarto', 'LOW', FALSE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada ) VALUES ('Andar ', 'LOW', TRUE);
INSERT INTO TB_TASK (name, prioridade, tarefa_finalizada) VALUES ('Organizar prateleira', 'MEDIUM', TRUE);
